### ISSUE TITLE
Correctly model eligibilty

### ISSUE THREAD

**Issue by nikhilwoodruff** [nikhilwoodruff/openfisca-uk#35]
Review how eligibility is modelled, and whether the reporting requirements on some benefits is the best way to account for take-up rates.

**Comment by nikhilwoodruff** [comment]
In summary, I think it's OK to have "is already reporting receipt" as an eligibility filter, despite no other major microsimulation model saying they do this, because right now "is already reporting" **is** an eligibility condition for the legacy benefits currently being phased out. None of the other microsimulation models report handling Universal Credit in their documentation, and we definitely want to. If we didn't have this requirement, we wouldn't be able to simulate Universal Credit, because it has the same eligibility rules as the benefits it replaces.

However, we do need to add the stochastic take-up method to Universal Credit. It's a tricky one, with a benefit still in experimental stages: at the moment we're restricting to already reporting claimants to be on the safe side, but it needs some thinking over.

**Comment by MaxGhenis** [comment]
Thanks @nikhilwoodruff, could you create a new issue for this one so we have it on hand?

> However, we do need to add the stochastic take-up method to Universal Credit. It's a tricky one, with a benefit still in experimental stages: at the moment we're restricting to already reporting claimants to be on the safe side, but it needs some thinking over.
